/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.visao;

import com.mycompany.controle.ControleSistema;
import com.mycompany.modelo.Computador;
import com.mycompany.modelo.VideoGame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eduardo.3946
 */
public class Listagem extends javax.swing.JFrame {

    /**
     * Creates new form Listagem
     */
    public Listagem() {
        initComponents();
        
        listartodos();
    }
    
    public static void listartodos(){
        DefaultTableModel defaulttablemodel = new DefaultTableModel();
        
        defaulttablemodel.addColumn("Informações");
        defaulttablemodel.addColumn("Categoria");
        
        tableListagem.setModel(defaulttablemodel);
        defaulttablemodel.setRowCount(0);
        
         for(int i = 0; i < ControleSistema.produtos.size(); i++){
             Object[] linha = new Object[defaulttablemodel.getColumnCount()];
             defaulttablemodel.addRow(linha);
             
             if(ControleSistema.produtos.get(i) instanceof Computador){
                 tableListagem.setValueAt(((Computador) ControleSistema.produtos.get(i)).getNome(), i, 0);
                 tableListagem.setValueAt("Computador", i, 1);
            }else if(ControleSistema.produtos.get(i) instanceof VideoGame){
                 tableListagem.setValueAt(((VideoGame) ControleSistema.produtos.get(i)).getNome(), i, 0);
                 tableListagem.setValueAt("Video Game", i, 1);
            }
             
         }
         
    }
    
    public static void listarComputador(){
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        
        defaultTableModel.addColumn("Nome");
        defaultTableModel.addColumn("Preço");
        defaultTableModel.addColumn("Memoria RAM");
        defaultTableModel.addColumn("Processador");
        
        tableListagem.setModel(defaultTableModel);
        
        defaultTableModel.setRowCount(0);
        int linhacont = 0;
        for(int i = 0; i < ControleSistema.produtos.size(); i++){
            if(ControleSistema.produtos.get(i) instanceof Computador){
                Object[] linha = new Object[defaultTableModel.getColumnCount()];
                defaultTableModel.addRow(linha);
                
                tableListagem.setValueAt(((Computador) ControleSistema.produtos.get(i)).getNome(), linhacont, 0);
                tableListagem.setValueAt(((Computador) ControleSistema.produtos.get(i)).getPreco(), linhacont, 1);
                tableListagem.setValueAt(((Computador) ControleSistema.produtos.get(i)).getMemoriaRAM(), linhacont, 2);
                tableListagem.setValueAt(((Computador) ControleSistema.produtos.get(i)).getProcessador(), linhacont, 3);
            
                linhacont++;
            }
        }
    }
    
    public static void listarVideoGame(){
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        
        defaultTableModel.addColumn("Nome");
        defaultTableModel.addColumn("Preço");
        defaultTableModel.addColumn("Plataforma");
        
        tableListagem.setModel(defaultTableModel);
        
        defaultTableModel.setRowCount(0);
        int linhacont = 0;
        for(int i = 0; i < ControleSistema.produtos.size(); i++){
            if(ControleSistema.produtos.get(i) instanceof VideoGame){
                Object[] linha = new Object[defaultTableModel.getColumnCount()];
                defaultTableModel.addRow(linha);
                
                tableListagem.setValueAt(((VideoGame) ControleSistema.produtos.get(i)).getNome(), linhacont, 0);
                tableListagem.setValueAt(((VideoGame) ControleSistema.produtos.get(i)).getPreco(), linhacont, 1);
                tableListagem.setValueAt(((VideoGame) ControleSistema.produtos.get(i)).getPlataforma(), linhacont, 2);
            
                linhacont++;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbCategorias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListagem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Computador", "Video Game" }));
        cbCategorias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCategoriasItemStateChanged(evt);
            }
        });
        cbCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriasActionPerformed(evt);
            }
        });

        tableListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Informaçoes", "Categorias"
            }
        ));
        jScrollPane1.setViewportView(tableListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(cbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCategoriasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCategoriasItemStateChanged
        // TODO add your handling code here:
        // corrigir
        //if(cbCategorias.getSelectedIndex() == 0){
            listartodos();
        //}else if{cbCategorias.getSelectedIndex() == 1){
            listarComputador(); 
        //}else if{cbCategorias.getSelectedIndex() == 2){
            listarVideoGame();
        
    }//GEN-LAST:event_cbCategoriasItemStateChanged

    private void cbCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCategorias;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable tableListagem;
    // End of variables declaration//GEN-END:variables
}
